service: time-to-leave-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs12.x
  environment:
    JWT_SECRET: ${self:custom.secrets.jwtSecret}
    DB: ${self:custom.secrets.db}

functions:
  get:
    handler: handler.get
    events:
      - http:
          path: get
          method: get
          cors: true

  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: post
          cors: true
